version: '3.6'

services:
  sut:
    tty: true
    build: .
    command: 
      - "yarn"
      - "test"
    volumes:
      - "./src:/app/src"
    environment:
      MONGO_URI: mongodb://username:abcd1234@mongo:27017/red_maceta?authSource=admin
    depends_on:
      - mongo
    ports:
      - "5000:5000"
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=abcd1234
