version: '3.6'

services:
  app:
    tty: true
    build: .
    command: 
      - "yarn"
      - "dev"
    volumes:
      - "./src:/app/src"
    environment:
      NODE_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27000:27017
